name: Autograding - Practical 12

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  autograding:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Student Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Run Autograding Test
        run: node tests/test.js
